thread 'cpal_wasapi_in' panicked at src/main.rs:52:99: called `Result::unwrap()` on an `Err` value: Evaluating #1249 "/emb_g_1/Gather" Gather
Caused by:
    0: Running legacy eval
    1: Invalid gather
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace